import { Student, TeacherProfile, AttendanceStats, AlertBanner, NavigationItem } from "@/types/teacher";

export const teacherProfile: TeacherProfile = {
  id: "teacher-001",
  name: "Sarah Mitchell",
  avatar: "SM",
  classroom: "Room 204",
  grade: "Grade 4A",
  school: "Lincoln Elementary School",
};

export const navigationItems: NavigationItem[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    icon: "LayoutDashboard",
    href: "/teachers",
  },
  {
    id: "attendance",
    label: "Attendance",
    icon: "CheckCircle2",
    href: "/teachers/attendance",
  },
  {
    id: "students",
    label: "Students",
    icon: "Users",
    href: "/teachers/students",
  },
];

export const attendanceStats: AttendanceStats = {
  totalClass: 28,
  arrived: 18,
  onBus: 7,
  absent: 3,
};

export const alertBanner: AlertBanner = {
  type: "warning",
  title: "3 Students Delayed",
  message: "Emma Johnson, Liam Chen, and Sofia Rodriguez are running 8-12 minutes late on Route A.",
  action: {
    label: "View Route",
    href: "/teachers/tracking",
  },
};

export const students: Student[] = [
  {
    id: "student-001",
    name: "Emma Johnson",
    avatar: "EJ",
    status: "delayed",
    eta: "8:45 AM",
    parentNotified: true,
  },
  {
    id: "student-002",
    name: "Liam Chen",
    avatar: "LC",
    status: "delayed",
    eta: "8:52 AM",
    parentNotified: true,
  },
  {
    id: "student-003",
    name: "Olivia Martinez",
    avatar: "OM",
    status: "present",
    timeArrived: "8:15 AM",
  },
  {
    id: "student-004",
    name: "Noah Williams",
    avatar: "NW",
    status: "present",
    timeArrived: "8:05 AM",
  },
  {
    id: "student-005",
    name: "Ava Garcia",
    avatar: "AG",
    status: "on-bus",
    eta: "8:38 AM",
  },
  {
    id: "student-006",
    name: "Lucas Rodriguez",
    avatar: "LR",
    status: "present",
    timeArrived: "8:22 AM",
  },
  {
    id: "student-007",
    name: "Mia Thompson",
    avatar: "MT",
    status: "present",
    timeArrived: "8:18 AM",
  },
  {
    id: "student-008",
    name: "Ethan Brown",
    avatar: "EB",
    status: "absent",
    parentNotified: true,
  },
  {
    id: "student-009",
    name: "Isabella Lee",
    avatar: "IL",
    status: "on-bus",
    eta: "8:41 AM",
  },
  {
    id: "student-010",
    name: "Mason White",
    avatar: "MW",
    status: "present",
    timeArrived: "8:12 AM",
  },
  {
    id: "student-011",
    name: "Sophia Anderson",
    avatar: "SA",
    status: "present",
    timeArrived: "8:08 AM",
  },
  {
    id: "student-012",
    name: "Jackson Taylor",
    avatar: "JT",
    status: "absent",
    parentNotified: false,
  },
  {
    id: "student-013",
    name: "Charlotte Davis",
    avatar: "CD",
    status: "present",
    timeArrived: "8:25 AM",
  },
  {
    id: "student-014",
    name: "Benjamin Miller",
    avatar: "BM",
    status: "on-bus",
    eta: "8:44 AM",
  },
  {
    id: "student-015",
    name: "Amelia Wilson",
    avatar: "AW",
    status: "present",
    timeArrived: "8:20 AM",
  },
  {
    id: "student-016",
    name: "Henry Moore",
    avatar: "HM",
    status: "delayed",
    eta: "8:48 AM",
    parentNotified: true,
  },
  {
    id: "student-017",
    name: "Evelyn Jackson",
    avatar: "EJ",
    status: "present",
    timeArrived: "8:10 AM",
  },
  {
    id: "student-018",
    name: "Alexander Martin",
    avatar: "AM",
    status: "present",
    timeArrived: "8:16 AM",
  },
  {
    id: "student-019",
    name: "Harper Garcia",
    avatar: "HG",
    status: "present",
    timeArrived: "8:28 AM",
  },
  {
    id: "student-020",
    name: "Michael Rodriguez",
    avatar: "MR",
    status: "absent",
    parentNotified: true,
  },
  {
    id: "student-021",
    name: "Abigail Brown",
    avatar: "AB",
    status: "present",
    timeArrived: "8:14 AM",
  },
  {
    id: "student-022",
    name: "Daniel Lee",
    avatar: "DL",
    status: "present",
    timeArrived: "8:26 AM",
  },
  {
    id: "student-023",
    name: "Ella White",
    avatar: "EW",
    status: "on-bus",
    eta: "8:46 AM",
  },
  {
    id: "student-024",
    name: "James Taylor",
    avatar: "JT",
    status: "present",
    timeArrived: "8:19 AM",
  },
  {
    id: "student-025",
    name: "Grace Harris",
    avatar: "GH",
    status: "present",
    timeArrived: "8:11 AM",
  },
  {
    id: "student-026",
    name: "William Clark",
    avatar: "WC",
    status: "present",
    timeArrived: "8:24 AM",
  },
  {
    id: "student-027",
    name: "Victoria Lewis",
    avatar: "VL",
    status: "on-bus",
    eta: "8:42 AM",
  },
  {
    id: "student-028",
    name: "Samuel Martinez",
    avatar: "SM",
    status: "present",
    timeArrived: "8:09 AM",
  },
];
